using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class ParticleSyncModel 
{
    [RealtimeProperty(1,false,true)]
    public bool _emissionEnabled;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class ParticleSyncModel : RealtimeModel {
    public bool emissionEnabled {
        get {
            return _emissionEnabledProperty.value;
        }
        set {
            if (_emissionEnabledProperty.value == value) return;
            _emissionEnabledProperty.value = value;
            InvalidateUnreliableLength();
            FireEmissionEnabledDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(ParticleSyncModel model, T value);
    public event PropertyChangedHandler<bool> emissionEnabledDidChange;
    
    public enum PropertyID : uint {
        EmissionEnabled = 1,
    }
    
    #region Properties
    
    private UnreliableProperty<bool> _emissionEnabledProperty;
    
    #endregion
    
    public ParticleSyncModel() : base(null) {
        _emissionEnabledProperty = new UnreliableProperty<bool>(1, _emissionEnabled);
    }
    
    private void FireEmissionEnabledDidChange(bool value) {
        try {
            emissionEnabledDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _emissionEnabledProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _emissionEnabledProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.EmissionEnabled: {
                    changed = _emissionEnabledProperty.Read(stream, context);
                    if (changed) FireEmissionEnabledDidChange(emissionEnabled);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _emissionEnabled = emissionEnabled;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
